name: "Terraform Plan"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Copy SSH public key from secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY_CONTENT }}" > ~/.ssh/azure_macbookpro.pub
          chmod 600 ~/.ssh/azure_macbookpro.pub

      # Skip Azure login in CI/CD
      # We'll only run terraform plan without applying

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          ARM_SKIP_PROVIDER_REGISTRATION: true
        continue-on-error: true

      - name: Comment on PR with Plan Output
        run: |
          echo "Terraform plan completed. Please apply manually from your local machine where you have Azure permissions."
